services:
  -
    name: "Test"
    matcher: "/api/v1"
    strategy: "WeightedRoundRobin"
    replicas:
      - 
        host: "http://localhost:8081"
        metadata:
          weight: 10
      - 
        host: "http://localhost:8082"
        metadata:
          weight: 5
  -
    name: "Test2"
    matcher: "/api/v2"
    strategy: "RoundRobin"
    replicas:
      - host: "http://localhost:8083"
      - host: "http://localhost:8084"
defaultStrategy: "RoundRobin"