services:
  -
    name: "Test"
    matcher: "/api/v1"
    strategy: "RoundRobin"
    replicas:
      - "http://localhost:8081"
      - "http://localhost:8082"
  -
    name: "Test2"
    matcher: "/api/v2"
    strategy: "RoundRobin"
    replicas:
      - "http://localhost:8083"
      - "http://localhost:8084"
defaultStrategy: "RoundRobin"